name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to the contents scope

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build # Replace with your build command if different

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Use the GITHUB_TOKEN secret
        publish_dir: ./public # Adjust this path to match your project's public directory
